import { StyleSheet } from "react-native";
import {COLORS} from "../../constants/colors";

export const agentsStyles = StyleSheet.create({
emptyCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    paddingVertical: 40,
    marginTop: 10,
    },
    emptyIconCircle: {
        width: 60,
        height: 60,
        borderRadius: 30,
        backgroundColor: '#F1F5F9',
        alignItems: 'center',
        justifyContent: 'center',
        marginBottom: 8,
    },
    appointmentCard: {
        backgroundColor: '#FFFFFF',
        borderRadius: 14,
        padding: 14,
        marginBottom: 10,
        borderWidth: 1,
        borderColor: '#E2E8F0',
        flexDirection: 'row',
        alignItems: 'center',
    },
    appointmentTimeBox: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 4,
        backgroundColor: '#FFF3E0',
        paddingHorizontal: 8,
        paddingVertical: 6,
        borderRadius: 8,
        marginRight: 12,
    },
    appointmentTimeText: {
        fontSize: 12,
        fontWeight: '700',
        color: COLORS.primary,
    },
    appointmentDetails: {
        flex: 1,
    },
    appointmentCustomerName: {
        fontSize: 14,
        fontWeight: '700',
        color: '#0F172A',
    },
    appointmentService: {
        fontSize: 12,
        color: '#64748B',
        marginTop: 2,
    },
    appointmentStatusBadge: {
        paddingHorizontal: 8,
        paddingVertical: 4,
        borderRadius: 6,
        backgroundColor: '#F1F5F9',
    },
    appointmentStatusText: {
        fontSize: 11,
        fontWeight: '700',
        color: '#64748B',
    },
    modalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0,0,0,0.5)',
        justifyContent: 'flex-end',
    },
    modalContent: {
        backgroundColor: '#FFFFFF',
        borderTopLeftRadius: 24,
        borderTopRightRadius: 24,
        padding: 20,
    },
    modalHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 16,
    },
    modalTitle: {
        fontSize: 18,
        fontWeight: '700',
        color: '#0F172A',
    },
    modalRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        paddingVertical: 10,
        borderBottomWidth: 1,
        borderBottomColor: '#F1F5F9',
    },
    modalLabel: {
        fontSize: 13,
        color: '#64748B',
    },
    modalVal: {
        fontSize: 13,
        fontWeight: '600',
        color: '#0F172A',
    },
    closeModalBtn: {
        backgroundColor: COLORS.primary,
        paddingVertical: 14,
        borderRadius: 12,
        alignItems: 'center',
        marginTop: 20,
    },
    closeModalBtnText: {
        color: '#FFFFFF',
        fontSize: 14,
        fontWeight: '700',
    },

    
    
    
    modalTokenBadge: {
        backgroundColor: '#EEF2FF',
        paddingHorizontal: 14,
        paddingVertical: 6,
        borderRadius: 10,
    },
    modalTokenBadgeText: {
        fontSize: 18,
        fontWeight: '800',
        color: '#1E293B',
    },
    modalServiceTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#0F172A',
    },
    modalStatusText: {
        fontSize: 13,
        color: '#64748B',
        marginBottom: 14,
        marginTop: 2,
    },
    
    
    modalActions: {
        marginTop: 20,
        gap: 10,
        marginBottom: 10,
    },
    modalActionBtn: {
        paddingVertical: 14,
        borderRadius: 12,
        alignItems: 'center',
        justifyContent: 'center',
    },
    modalActionBtnText: {
        color: '#FFFFFF',
        fontSize: 14,
        fontWeight: '700',
    },

    profileCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 18,
    padding: 20,
    alignItems: 'center',
    marginBottom: 20,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    },
    avatarCircle: {
        width: 68,
        height: 68,
        borderRadius: 34,
        backgroundColor: '#FFF3E0',
        alignItems: 'center',
        justifyContent: 'center',
        marginBottom: 10,
        borderWidth: 2,
        borderColor: COLORS.primary,
    },
    avatarText: {
        fontSize: 28,
        fontWeight: '800',
        color: COLORS.primary,
    },
    profileName: {
        fontSize: 18,
        fontWeight: '800',
        color: '#0F172A',
    },
    profileEmail: {
        fontSize: 13,
        color: '#64748B',
        marginTop: 2,
    },
    roleBadge: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#FFF3E0',
        paddingHorizontal: 12,
        paddingVertical: 5,
        borderRadius: 20,
        marginTop: 10,
        gap: 4,
    },
    roleBadgeText: {
        fontSize: 11,
        fontWeight: '700',
        color: COLORS.primary,
        letterSpacing: 0.5,
    },
    cardContainer: {
        backgroundColor: '#FFFFFF',
        borderRadius: 16,
        padding: 16,
        borderWidth: 1,
        borderColor: '#F1F5F9',
        marginBottom: 16,
    },
    infoRow: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingVertical: 4,
    },
    infoIconBox: {
        width: 36,
        height: 36,
        borderRadius: 10,
        backgroundColor: '#FFF3E0',
        alignItems: 'center',
        justifyContent: 'center',
    },
    infoLabel: {
        fontSize: 11,
        fontWeight: '600',
        color: '#94A3B8',
        textTransform: 'uppercase',
    },
    infoValue: {
        fontSize: 14,
        fontWeight: '700',
        color: '#0F172A',
        marginTop: 1,
    },
    divider: {
        height: 1,
        backgroundColor: '#F1F5F9',
        marginVertical: 10,
    },
    switchModeButton: {
        backgroundColor: '#FFFFFF',
        borderRadius: 14,
        padding: 16,
        flexDirection: 'row',
        alignItems: 'center',
        borderWidth: 1,
        borderColor: '#E2E8F0',
        marginBottom: 12,
    },
    switchModeTitle: {
        fontSize: 14,
        fontWeight: '700',
        color: '#0F172A',
    },
    switchModeSubtitle: {
        fontSize: 12,
        color: '#64748B',
        marginTop: 2,
    },
    signOutButton: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 14,
        borderRadius: 12,
        borderWidth: 1,
        borderColor: '#FEE2E2',
        backgroundColor: '#FEF2F2',
        marginTop: 8,
        marginBottom: 20,
        gap: 6,
    },
    signOutButtonText: {
        color: '#EF4444',
        fontSize: 14,
        fontWeight: '700',
    },

        
    modalCard: {
        backgroundColor: '#FFFFFF',
        borderTopLeftRadius: 24,
        borderTopRightRadius: 24,
        padding: 20,
    },
    
    modalTokenText: {
        fontSize: 22,
        fontWeight: '800',
        color: COLORS.primary,
    },
    
    
    modalDetailRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        paddingVertical: 10,
        borderBottomWidth: 1,
        borderBottomColor: '#F1F5F9',
    },

    modalBtn: {
        paddingVertical: 14,
        borderRadius: 12,
        alignItems: 'center',
        justifyContent: 'center',
    },
    modalBtnText: {
        color: '#FFFFFF',
        fontSize: 14,
        fontWeight: '700',
    },

    formContainer: {
    backgroundColor: '#FFFFFF',
    borderRadius: 18,
    padding: 18,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    },
    formSectionTitle: {
        fontSize: 15,
        fontWeight: '700',
        color: '#0F172A',
        marginBottom: 12,
    },
    serviceCardsGrid: {
        gap: 8,
    },
    serviceOptionCard: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingVertical: 12,
        paddingHorizontal: 14,
        borderRadius: 12,
        backgroundColor: '#F8FAFC',
        borderWidth: 1,
        borderColor: '#E2E8F0',
    },
    serviceOptionCardActive: {
        backgroundColor: '#FFF3E0',
        borderColor: COLORS.primary,
    },
    serviceOptionTitle: {
        fontSize: 13,
        fontWeight: '600',
        color: '#334155',
        marginLeft: 10,
        flex: 1,
    },
    serviceOptionTitleActive: {
        color: COLORS.primary,
        fontWeight: '700',
    },
    inputLabel: {
        fontSize: 12,
        fontWeight: '600',
        color: '#64748B',
        marginBottom: 6,
        marginTop: 12,
    },
    textInput: {
        backgroundColor: '#F8FAFC',
        borderWidth: 1,
        borderColor: '#E2E8F0',
        borderRadius: 10,
        paddingHorizontal: 14,
        paddingVertical: 10,
        fontSize: 14,
        color: '#0F172A',
    },
    generateButton: {
        backgroundColor: COLORS.primary,
        borderRadius: 14,
        paddingVertical: 14,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 8,
        marginTop: 20,
    },
    generateButtonText: {
        color: '#FFFFFF',
        fontSize: 15,
        fontWeight: '700',
    },
    primaryBtn: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 12,
        borderRadius: 12,
        gap: 6,
    },
    primaryBtnText: {
        color: '#FFFFFF',
        fontSize: 14,
        fontWeight: '700',
    },
});